language:
  python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.7

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install flake8 pytest coverage coveralls pytest-cov

script:
  - flake8 wifiPassword
  - python setup.py install
  - py.test --cov-report=xml  tests/test.py

after_success:
  coveralls